### ISSUE TITLE
Impossible to verify the signature

### ISSUE THREAD

**Issue by dmitry-kanunnikoff** [TrustWallet/TrustSDK-Android#10]
Good afternoon.

I've tried to verify the signature (and to get the signer's address), but, unfortunately, I couldn't do that (I get wrong address). 

Signature created by: `Trust.signMessage()`

I've used this method for recovering: [link](https://github.com/web3j/web3j/blob/ed2ca03335ad2cb3316314303746b70b456b0d68/crypto/src/test/java/org/web3j/crypto/ECRecoverTest.java)

And two more things:
1. signature verification also fail on the https://etherscan.io/verifySig
2. signatures, created for the same message on Android and iOS, are different

**Comment by madcake** [comment]
If you need simple message use mew.
As example:
{
  "address": "0x15f4d9bed894e2e426d65e3df1480c61fb131a57",
  "msg": "Hello!",
  "sig": "0xd2500e69c67ca725532709ee909a5e3e9f2280710a796feccb4861f7845a6d815fe391d34625e696f689a4e3c5a3231db0ef2427e1eb205da06ac3dc579d5b6e1b",
  "version": "1",
  "signer": "MEW"
}

**Comment by dmitry-kanunnikoff** [comment]
@madcake Thanks for response.

MEW - is it a MyEtherWallet? 

I need to use TrustWallet. And to verify that user has an active wallet address in the TrustWallet app - an address, that he used in the registration process in our project's web-version. So I need to request signMessage() before I let the user to request signTransaction()'s in the future.

All works fine on iOS, but I get a wrong signature on Android.

Can you help me? What I need to do? I've lost a lot of working time to learn and find any solutions. So, if it is possible, please, share more details.

**Comment by dmitry-kanunnikoff** [comment]
@madcake tell me, please, what I need to do to get the right signature from the TrustWallet app on Android?
@vikmeup has suggested to use signPersonalMessage(), so, please, help me to achieve my goals by using this method.

I do like this:

```
signPersonalMessageCall = Trust.signPersonalMessage()
                .message("my message to be signed")
                .call(this)
```

Next I try to recover the address like [this](https://github.com/web3j/web3j/blob/ed2ca03335ad2cb3316314303746b70b456b0d68/crypto/src/test/java/org/web3j/crypto/ECRecoverTest.java).

But I get a wrong result. Thanks in advance.

**Comment by dmitry-kanunnikoff** [comment]
Thank you very much in the solving of this issue!
