### ISSUE TITLE
New version of app no longer has testnet

### ISSUE THREAD

**Issue by jessechahal** [TrustWallet/TrustSDK-Android#11]
So one of the benefits of this app is to help students learn about crypto. This app no longer seems to support test app. It would be nice if all releases of the app were also saved in github so at the very least i could get students to use the apk file from github. 

I noticed that there does not appear to be a build system within the repo. Are the apk builds made manually? Could we not just leverage travis and have apks built and pushed to github+ other places.

**Comment by vikmeup** [comment]
Can you message me on telegram @vikmeup? I will send you enough real tokens to educate new students.
