### ISSUE TITLE
Micro-payments in bulk without consent

### ISSUE THREAD

**Issue by hjoshi123** [trustwallet/TrustSDK-Android#15]
Hey Guys, I am building a dapp and want the user to be able to **set a limit on spending and in the background, the dapp should be able to connect to wallet and make transactions on micropayments without users consent until a set limit is reached.** Basically, user approves the one transaction and sets a limit for spending, the transactions happen in background while the user uses the app until the spending limit is reached. 
I loved the SDK and would love to hear ideas as to how to achieve this.

**Comment by adigupta13** [comment]
Useful usecase. Would love to see this implemented. Micro transactions need this functionality in wallets
