### ISSUE TITLE
Discussion about contributing project

### ISSUE THREAD

**Issue by gouri-panda** [trustwallet/TrustSDK-Android#30]
HI! Nice projects. I want to work on this project. Are there any issues are there like to contribute and apologies for creating this issue. I can't find any communication and help channel.

**Comment by MastaBook** [comment]
> HI! Nice projects. I want to work on this project. Are there any issues are there like to contribute and apologies for creating this issue. I can't find any communication and help channel.

Я запутался и немогу вообще не с чем разобратся((потерялся в этом сайте но очень хочу понять а все никак ((

**Comment by wieseaka** [comment]
I need to make an contract for Iehtercan how do i do that
