### ISSUE TITLE
Failed to resolve: com.github.TrustWallet:TrustSDK-Android:0.01.13

### ISSUE THREAD

**Issue by nb312** [trustwallet/TrustSDK-Android#4]
I have set the maven  in the  gradle of  project 
```
 maven {
          url "https://jitpack.io"
        }
```
and dependencies
```
 implementation 'com.github.TrustWallet:TrustSDK-Android:0.01.13'
```
but it has an error when building the project, showing at below: 

```
Failed to resolve: com.github.TrustWallet:TrustSDK-Android:0.01.13
```
as you can see, the version is different from your describes with "$version", but I don't know which version to choose.  thanks man！

**Comment by vikmeup** [comment]
@madcake

**Comment by madcake** [comment]
Try once more.

**Comment by madcake** [comment]
Recheck gradle config. Example from real project:

apply plugin: 'kotlin-android-extensions'

buildscript {
    ext.kotlin_version = '1.2.20'

    repositories {
        google()
        jcenter()
        mavenCentral()
        **maven { url 'https://jitpack.io' }**
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
        classpath "io.realm:realm-gradle-plugin:5.1.0"
        classpath 'com.google.gms:google-services:3.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        jcenter()
        google()
        mavenCentral()

        **maven { url 'https://jitpack.io' }**

    }
}
