### ISSUE TITLE
My bitcoin and litecoin statement is empty despite having received transactions

### ISSUE THREAD

**Issue by PierreVieira** [trustwallet/TrustSDK-Android#42]
Hello developers friends. I hope to be opening this issue in the correct repository.
I can't consult my bitcoin and litecoin extract anymore, I noticed this error occurred after I renamed my wallet.
Earlier I had an extract for these cryptocurrencies, however they are gone. I've tried obvious solutions like closing and opening the app and checking my internet connection, but I still have the same problem (my internet has no connection issues).
**I can still consult my extract of other cryptocurrencies like bittorrent, nano and ADA normally.**
For research purposes I am using android 11 and I have the latest version of the app.

<div align = "center">
<img width="280" src="https://user-images.githubusercontent.com/49538805/122687790-a83e2a00-d1ee-11eb-884b-65b348525c33.png"> <img width="280" src="https://user-images.githubusercontent.com/49538805/122687804-be4bea80-d1ee-11eb-9d76-5a566d422fc1.png">
</div>

**Comment by vikmeup** [comment]
Transactions list might not be available at time, we currently working to improve this feature, feel free to use block explorer to see correct transitions list
