### ISSUE TITLE
Transaction not being sent to Smart Contract

### ISSUE THREAD

**Issue by balak590** [trustwallet/TrustSDK-Android#43]
When we put "to" address as pancake router, and provide coin and token, the transaction is not being sent to the smart contract rather its being sent to token address "BUSD". Can you kindly check on this one and rectify it?

Without Token:
https://bscscan.com/tx/0x156c6f023c21a19fc91efb4e53b7a89020c7d2874e0f4dd3d651d8f12eb8e2b0

With BUSD as Token:
https://bscscan.com/tx/0x4a985ed0b9e541ad2524713dd9187192afcb9575ce30eab327e57967eeda097e

**Comment by Asif-Info** [comment]
hello Sir,
  Trust Wallet Send Transaction Page open but redirect to google play store ,
 sir, how to resolve this issue

**Comment by vikmeup** [comment]
https://community.trustwallet.com/t/trustsdk-is-discontinued/213116
