### ISSUE TITLE
Questions on the functional

### ISSUE THREAD

**Issue by dmitry-kanunnikoff** [TrustWallet/TrustSDK-Android#8]
Good afternoon.

Let me ask you a couple of questions:
1. Is it possible to check whether the user is authorized in the wallet?
2. Is it possible to get the address of the user's wallet?

Thank you in advance.

**Comment by vikmeup** [comment]
@dmitry-kanunnikoff once you receive signed message you can recover signed address.

**Comment by dmitry-kanunnikoff** [comment]
> @dmitry-kanunnikoff once you receive signed message you can recover signed address.

@vikmeup I'm sorry, but could you tell me how I can do this? Maybe there is some documentation?

**Comment by dmitry-kanunnikoff** [comment]
And tell me, please, that in the end comes in response.result for, say, a signTransaction()? Is this the transaction ID hash?

**Comment by madcake** [comment]
The signed transaction is returned - the transaction data is serialized rlp, encrypted and again serialized rlp. These data can be deserialized and get a signature and transaction data. Look at https://github.com/ethereum/wiki/wiki/RLP.

**Comment by dmitry-kanunnikoff** [comment]
@madcake Thank you very much for your reply! I'll look in this direction.

**Comment by dmitry-kanunnikoff** [comment]
@madcake Good afternoon!
Thank you for your help!
I was able to decode the presentation of the transaction. However, I can not get the value of the 'from' field. An error pops up: "Invalid transaction v,r,s values".
It was discussed here: https://github.com/ethereum/go-ethereum/issues/14599.
But, as I understand, the solution boils down to the fact that now you need to specify the identifier of the chain.
Please tell me how can I get this chain ID with only a signed transaction?
Thank you in advance for any help!


https://pix.my/eQ9z1j

**Comment by dmitry-kanunnikoff** [comment]
I found that, it turns out, the chain ID is not an arbitrary number. Turned to this list, and was able to pick up the ID I needed: https://ethereum.stackexchange.com/a/17101/46174
The problem is solved.
Thank you very much, guys!

**Comment by dmitry-kanunnikoff** [comment]
@madcake Good afternoon.

I apologize for the disturbance. Tell me, please, how can I get the address of the wallet from the signed message (Trust.signMessage())? And is it even possible?

With the transaction, I did this: 
`val tx = Geth.newTransactionFromRLP(Numeric.hexStringToByteArray(response.result))`

 But how to decode the data from the signed message?

**Comment by madcake** [comment]
Look at 'recovery'

**Comment by dmitry-kanunnikoff** [comment]
@madcake I am sorry, but I couldn't find the direction where to search.
Tell me, please, where I need to search 'recovery'? Can you post the direct link?

**Comment by dmitry-kanunnikoff** [comment]
@madcake Maxim, could you, please, share more details?
