### ISSUE TITLE
Sign message return incorrect result

### ISSUE THREAD

**Issue by emn178** [TrustWallet/TrustSDK-Android#9]
Latest Android app can't sign correctly by web3.eth.sign. It returns incorrect result with or without prefix:
\x19Ethereum Signed Message:\n. I can't get correct signer by ecrecover. Previous version and iOS can work with prefix.

I also try web3.personal.sign but still not work.

```JavaScript
let message = 'dba804b179bcef94d77dda506abbe02463d99c4b92e9d6567c0c7663ea0e2d82'

// prefix
const buffer = Buffer.concat([new Buffer(`\x19Ethereum Signed Message:\n${message.length / 2}`), new Buffer(message, 'hex')]);
message = keccak256(buffer);

// try eth.sign
this.web3.eth.sign(singer, `0x${message}`, callback);

// try personal.sign
this.web3.personal.sign(`0x${message}`, singer, null, callback);
```

I tried:
prefix + eth.sign
eth.sign without prefix
prefix + personal.sign
personal.sign without prefix

all failed.

**Comment by vikmeup** [comment]
why do you add `0x` in the beginning?

**Comment by vikmeup** [comment]
@emn178 https://danfinlay.github.io/js-eth-personal-sign-examples/ can you take a look at this example, does it work for you on the android app?

**Comment by emn178** [comment]
keccak256 return string here.
```JavaScript
message = keccak256(buffer);
// 04389357a55db5381567bf1c0ab518bf6dde2e137ea9c2d99e85079dfb41861b
```

This usage worked previous version

**Comment by emn178** [comment]
I forked https://danfinlay.github.io/js-eth-personal-sign-examples/ and changed it from `console.log` to print in web page.

I open it in Trust and other wallets and click `personal_ecRecover`.

Trust failed to ecRecover
![screenshot_20180921-164919](https://user-images.githubusercontent.com/3477613/45870965-cddc4180-bdbe-11e8-8eae-10f693d7a8f3.png)



The other wallet passed
![screenshot_20180921-164904](https://user-images.githubusercontent.com/3477613/45870966-ce74d800-bdbe-11e8-9f3c-5abb9925eca9.png)

**Comment by vikmeup** [comment]
@emn178 I don't think we have recover implemented.

@madcake can you implement this? 

@hewigovens can you help @madcake with this?

**Comment by vikmeup** [comment]
@emn178 does other methods works for you? besides recover

**Comment by emn178** [comment]
Sorry, I didn't notice this test uses personal_ecRecover from provider. This is not my point. My point is signature can not recover signer. I will try to give an test case later.

**Comment by emn178** [comment]
I can reproduce my problem and setup a test case. Please open https://emn178.github.io/js-eth-personal-sign-examples/index.html and click `personal_sign` button.

Trust failed to recover signer
![screenshot_20180921-173940](https://user-images.githubusercontent.com/3477613/45873919-26630d00-bdc6-11e8-9b37-ab29e2a6d550.png)

The other wallet passed
![screenshot_20180921-173151](https://user-images.githubusercontent.com/3477613/45873920-26630d00-bdc6-11e8-8ddc-103d231eb03b.png)

source code:
https://github.com/emn178/js-eth-personal-sign-examples/blob/master/index.js#L27-L64

**Comment by madcake** [comment]
How did you get this line:
0x99ab1f3b1111a7eb8fbb9797e5b05c2daa11ec771414ae3f9164ccf189c1cb33?

On android we wait string in hex:
```java
byte[] data = Numeric.hexStringToByteArray(message.value);
String formattedMessage = "\u0019Ethereum Signed Message:\n" + data.length + new String(data);
data = CryptoUtils.sha3(formattedMessage.getBytes());
return walletRepository.signMessage(wallet, password, account, data, false);
```

**Comment by emn178** [comment]
It's a hash of a string. I think the problem may be that you consider it's a readable text and convert it to a string. Try to process it in binary.

**Comment by madcake** [comment]
Fixed

**Comment by emn178** [comment]
eth.sign seems to have the same problem. Can you please check?

**Comment by emn178** [comment]
I add the other test case. Please click click `eth_sign` button. The result is the same with `personal_sign`. Trust failed but others passed.

source code: https://github.com/emn178/js-eth-personal-sign-examples/blob/master/index.js#L16-L37

**Comment by vikmeup** [comment]
@emn178 can you download latest build and test this out?

**Comment by emn178** [comment]
Yes, I have downloaded and tested on 1.6.132

**Comment by madcake** [comment]
Fixed. Check the other cases that interest you please. If other is ok I will release.

**Comment by emn178** [comment]
release please
